services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    Gupalo\ChangeLogBundle\Controller\:
        resource: '../../Controller/'
        tags: [ 'controller.service_arguments' ]

    Gupalo\ChangeLogBundle\Repository\ChangeLogRepository:
        autowire: true

    Gupalo\ChangeLogBundle\EventSubscriber\ChangeLogEventSubscriber:
        tags:
            - name: 'doctrine.event_subscriber'

